dist    : trusty
language: java
jdk     : oraclejdk8

addons:
  sonarcloud:
    organization: "ivmikhail"
    token:
      secure: "**************************" # encrypted value of your token

script:
  - ./gradlew sonarqube
